// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MonadDefense
 * @dev A simple smart contract to manage game initialization payments on Monad testnet.
 */
contract MonadDefense {
    address public owner;
    uint256 public gameStartFee;
    uint256 public totalGamesStarted;
    
    // Mapping from gameId to the player's address
    mapping(uint256 => address) public gamePlayers;
    // Mapping from gameId to the payment amount
    mapping(uint256 => uint256) public gamePayments;
    // Mapping from gameId to whether the game has started
    mapping(uint256 => bool) public isGameActive;

    event GameStarted(address indexed player, uint256 indexed gameId, uint256 feePaid, uint256 timestamp);
    event GameEnded(address indexed player, uint256 indexed gameId, uint256 score, uint256 timestamp);
    event FeeUpdated(uint256 oldFee, uint256 newFee);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can call this function");
        _;
    }

    constructor() {
        owner = msg.sender;
        // Default start fee: 0.01 MON (10^16 Wei)
        gameStartFee = 0.01 ether;
    }

    /**
     * @dev Starts a game. Requires sending the gameStartFee in MON.
     * @param gameId Unique identifier for the game session generated by the client/backend.
     */
    function startGame(uint256 gameId) external payable {
        require(msg.value >= gameStartFee, "Insufficient MON sent to start game");
        require(!isGameActive[gameId], "Game ID already active");

        gamePlayers[gameId] = msg.sender;
        gamePayments[gameId] = msg.value;
        isGameActive[gameId] = true;
        totalGamesStarted++;

        emit GameStarted(msg.sender, gameId, msg.value, block.timestamp);
    }

    /**
     * @dev Records that a game has ended (for historical/analytic logging).
     * @param gameId The game ID that has ended.
     * @param score The high score reached by the player.
     */
    function endGame(uint256 gameId, uint256 score) external {
        require(isGameActive[gameId], "Game is not active");
        // For simplicity, anyone or the owner can submit. Let's restrict it to the player who started it or owner.
        require(msg.sender == gamePlayers[gameId] || msg.sender == owner, "Not authorized to end this game");

        isGameActive[gameId] = false;

        emit GameEnded(gamePlayers[gameId], gameId, score, block.timestamp);
    }

    /**
     * @dev Allows the owner to update the game start fee.
     * @param _newFee New fee in Wei.
     */
    function updateGameStartFee(uint256 _newFee) external onlyOwner {
        uint256 oldFee = gameStartFee;
        gameStartFee = _newFee;
        emit FeeUpdated(oldFee, _newFee);
    }

    /**
     * @dev Allows the owner to withdraw the contract balance.
     */
    function withdraw() external onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "No funds to withdraw");
        
        (bool success, ) = payable(owner).call{value: balance}("");
        require(success, "Withdrawal failed");
    }

    /**
     * @dev Helper to change ownership.
     */
    function transferOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "Invalid new owner address");
        owner = _newOwner;
    }
}
